[package]
name = "sumi-core"
description = "Convert PDF colors to grayscale or monochrome without rasterizing"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
lopdf.workspace = true
flate2.workspace = true
zune-jpeg.workspace = true
thiserror.workspace = true

[dev-dependencies]
flate2.workspace = true
